### ISSUE TITLE
Doesn't work with mosaico

### ISSUE THREAD

**Issue by jmcclelland** [TechToThePeople/privacier#1]
This extension doesn't seem to work with Mosaico.

With Mosaico, the code turning off the default tracking setting is only triggered if you happen to click Advanced Settings.

Furthermore, the mailing is saved almost immediately when you first start it, so by the time you might click on advanced settings, the tracking has already been saved and set to on.

I finally achieved the goal by implementing the suggestion at the [bottom of the stack exchange thread](https://civicrm.stackexchange.com/a/34177/409) by simply add:

```
function mymodule_civicrm_pre($op, $objectName, $id, &$params) {
  if ($objectName == 'Mailing' && $op == 'create') {
    $params['url_tracking'] = 0;
  }
}
```

**Comment by tttp** [comment]
Awesome you solved it

Could you submit a pr?

**Comment by jmcclelland** [comment]
Woops! I just realized that this feature is now part of core. Administer -> CiviMail -> CiviMail Component settings:

![tracking-options](https://user-images.githubusercontent.com/4511942/135276870-e1a8d197-2f2a-4f9c-9d10-1bfa19465c0d.png)
